server:
  port: 8080

spring:
  application:
    name: home-test
  security:
    filter:
      dispatcher-types: REQUEST,ERROR
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:postgresql://localhost:5432/travel_list
#    username: postgres
#    password: admin
    url: jdbc:mysql://localhost:3306/travel_list?useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
debug: true

security:
  authentication:
    jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
      base64-secret: MjI3YzU0OTQ4OTg4YWM4MmM1YWU1NzIyNWVkZTdmM2NjM2Y4NTUzZTdlZjEyZmNjMWQyMDlkOGYzYTEyM2Q3MmMyNjM2ZGM5ZGNkZWI1MDU1NzVhNTRlNGJhMDBlZDkyOTQ4M2UzZjgyZjM2OTFiYWYyNzA4ZTgyZGUxNjgxNWQ=
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000